require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'rn3d' do
  use_unimodules!

  pre_install do |installer|
    installer.pod_targets.each do |target|
      if target.name == "UMPermissionsInterface"
        # https://github.com/expo/expo/issues/6477
        target.dependent_targets << installer.pod_targets.select{|t| t.pod_name == 'UMCore'}.first
      end
      if target.name == 'UMReactNativeAdapter'
        target.dependent_targets << installer.pod_targets.select{|t| t.pod_name == 'React-CoreModules'}.first
      end
    end
  end
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'rn3dTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rn3d-tvOS' do
  # Pods for rn3d-tvOS

  target 'rn3d-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
